[project]
name = "assistants-demo"
version = "0.0.1"
description = "Example of configuration and assistants using ReAct and Supervisor agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.25",
    "langchain-anthropic>=0.3.14",
    "langchain-community>=0.3.24",
    "langchain-openai>=0.3.18",
    "langchain-tavily>=0.2.0",
    "langgraph>=0.4.7",
    "langgraph-cli[inmem]>=0.2.10",
    "langgraph-supervisor>=0.0.27",
    "pydantic>=2.11.5",
    "python-dotenv>=1.1.0",
    "typing-extensions>=4.13.2",
    "yfinance>=0.2.61",
]
